/**
 * Stage 8 — Payment / Billing
 *
 * Tables:
 *   subscription_plans       — server-controlled plan catalog
 *   subscriptions            — per-user subscription state machine
 *   payment_intents          — individual checkout/payment attempts
 *   billing_webhook_events   — idempotent webhook log (replay protection)
 *
 * Monetary amounts are always stored as integer minor units (e.g. kobo for NGN).
 * Currency is always explicit — no implicit defaults at query time.
 *
 * Security invariants:
 *   - amount_minor and currency are snapshotted from the server-side plan catalog
 *     at intent creation time; they cannot be supplied or modified by the client.
 *   - provider_reference, provider_payment_id, and authorization_url are set only
 *     by backend logic — never read from request bodies.
 *   - billing_webhook_events enforces UNIQUE(provider, event_id) — duplicate
 *     webhook deliveries are rejected at the DB constraint level.
 *   - subscriptions.UNIQUE(user_id) — one subscription record per user.
 */

import {
  pgTable,
  pgEnum,
  text,
  integer,
  boolean,
  timestamp,
  jsonb,
  index,
  unique,
  check,
} from "drizzle-orm/pg-core";
import { users } from "./users.js";

// ─── Enums ────────────────────────────────────────────────────────────────────

export const subscriptionStatusEnum = pgEnum("subscription_status", [
  "trialing",
  "active",
  "past_due",
  "cancelled",
  "expired",
]);

export const paymentIntentStatusEnum = pgEnum("payment_intent_status", [
  "pending",
  "processing",
  "succeeded",
  "failed",
  "refunded",
]);

// ─── subscription_plans ───────────────────────────────────────────────────────

export const subscriptionPlans = pgTable("subscription_plans", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),

  /** Amount in integer minor units (e.g. kobo for NGN). 0 = free plan. */
  amountMinor: integer("amount_minor").notNull(),

  /** ISO 4217 currency code. */
  currency: text("currency").notNull().default("NGN"),

  /** 'monthly' | 'yearly' | 'one_time' */
  billingInterval: text("billing_interval").notNull().default("monthly"),

  /** When false the plan is not offered for new checkouts. */
  isActive: boolean("is_active").notNull().default(true),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ─── subscriptions ────────────────────────────────────────────────────────────

export const subscriptions = pgTable(
  "subscriptions",
  {
    id: text("id").primaryKey(),

    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    planId: text("plan_id")
      .notNull()
      .references(() => subscriptionPlans.id),

    status: subscriptionStatusEnum("status").notNull().default("active"),

    /**
     * Opaque ID from the payment provider.
     * NULL for free-plan subscriptions.
     */
    providerSubscriptionId: text("provider_subscription_id"),

    currentPeriodStart: timestamp("current_period_start", { withTimezone: true }),
    currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),

    /** Set when the user cancels — subscription continues until currentPeriodEnd. */
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    /** One subscription record per user. */
    unique("subscriptions_user_id_unique").on(t.userId),
    index("subscriptions_status_idx").on(t.status),
    index("subscriptions_plan_idx").on(t.planId),
  ],
);

// ─── payment_intents ──────────────────────────────────────────────────────────

export const paymentIntents = pgTable(
  "payment_intents",
  {
    id: text("id").primaryKey(),

    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    planId: text("plan_id")
      .notNull()
      .references(() => subscriptionPlans.id),

    subscriptionId: text("subscription_id").references(() => subscriptions.id),

    /**
     * Snapshot of the plan's amount_minor at intent creation time.
     * Immune to subsequent plan price changes.
     * Set by the server — never from client input.
     */
    amountMinor: integer("amount_minor").notNull(),

    /** ISO 4217 currency code — snapshot from plan. */
    currency: text("currency").notNull(),

    status: paymentIntentStatusEnum("status").notNull().default("pending"),

    /**
     * Reference generated by this backend and sent to the payment provider.
     * Used to correlate provider webhooks back to this intent.
     * UNIQUE ensures one active intent per reference.
     */
    providerReference: text("provider_reference").unique(),

    /**
     * Provider-assigned payment ID — set only by the webhook handler.
     * Never accepted from client requests.
     */
    providerPaymentId: text("provider_payment_id"),

    /** Checkout URL returned by the provider's initialise call. */
    authorizationUrl: text("authorization_url"),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("payment_intents_user_idx").on(t.userId),
    index("payment_intents_status_idx").on(t.status),
    index("payment_intents_reference_idx").on(t.providerReference),
    check("payment_intents_amount_non_negative", sql`${t.amountMinor} >= 0`),
  ],
);

// ─── billing_webhook_events ───────────────────────────────────────────────────

export const billingWebhookEvents = pgTable(
  "billing_webhook_events",
  {
    id: text("id").primaryKey(),

    /** e.g. 'paystack' */
    provider: text("provider").notNull(),

    /** Provider-assigned unique event ID — UNIQUE(provider, event_id) prevents replays. */
    eventId: text("event_id").notNull(),

    /** e.g. 'charge.success' */
    eventType: text("event_type").notNull(),

    /** Raw provider payload — stored for audit and reprocessing. */
    payload: jsonb("payload").notNull(),

    /** NULL = received but not yet processed. Set when processing completes. */
    processedAt: timestamp("processed_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    /** Replay protection: duplicate (provider, event_id) pairs are rejected. */
    unique("billing_webhook_events_unique").on(t.provider, t.eventId),
    index("billing_webhook_events_provider_idx").on(t.provider),
    index("billing_webhook_events_event_type_idx").on(t.eventType),
  ],
);

// ─── Inferred types ───────────────────────────────────────────────────────────

export type SubscriptionPlan = typeof subscriptionPlans.$inferSelect;
export type NewSubscriptionPlan = typeof subscriptionPlans.$inferInsert;
export type Subscription = typeof subscriptions.$inferSelect;
export type NewSubscription = typeof subscriptions.$inferInsert;
export type PaymentIntent = typeof paymentIntents.$inferSelect;
export type NewPaymentIntent = typeof paymentIntents.$inferInsert;
export type BillingWebhookEvent = typeof billingWebhookEvents.$inferSelect;
export type NewBillingWebhookEvent = typeof billingWebhookEvents.$inferInsert;

export type SubscriptionStatus = (typeof subscriptionStatusEnum.enumValues)[number];
export type PaymentIntentStatus = (typeof paymentIntentStatusEnum.enumValues)[number];

// sql is needed for the check constraint
import { sql } from "drizzle-orm";
