import { pgTable, text, timestamp, pgEnum } from "drizzle-orm/pg-core";

/**
 * Account types.
 *
 * PUBLIC — self-registered via Clerk:
 *   employer, provider
 *
 * INTERNAL — provisioned through a controlled backend process only.
 *   owner, system_admin, verification_team, support_team, moderation_team
 *
 * The public registration endpoint enforces that only the public types
 * can be chosen; internal types are never assignable via public API.
 */
export const accountTypeEnum = pgEnum("account_type", [
  "employer",
  "provider",
  "owner",
  "system_admin",
  "verification_team",
  "support_team",
  "moderation_team",
]);

/**
 * Provider specialisation — only populated when account_type = 'provider'.
 * Extensible: add new values via migration without touching route logic.
 */
export const providerKindEnum = pgEnum("provider_kind", ["artisan", "professional"]);

/** Lifecycle status of a PMP account. */
export const userStatusEnum = pgEnum("user_status", ["active", "suspended", "deleted"]);

export const users = pgTable("users", {
  /** Stable internal PMP identifier (UUID generated by application). */
  id: text("id").primaryKey(),

  /**
   * Clerk user ID — the external identity reference.
   * This is the only link between Clerk and PMP PostgreSQL.
   * Never store Clerk secret keys here.
   */
  clerkUserId: text("clerk_user_id").notNull().unique(),

  /** The kind of PMP account. Source of truth for authorization. */
  accountType: accountTypeEnum("account_type").notNull(),

  /**
   * Artisan vs. professional — only set for provider accounts.
   * null for employer and all internal account types.
   */
  providerKind: providerKindEnum("provider_kind"),

  /** Lifecycle status. Suspended/deleted users are rejected at auth time. */
  status: userStatusEnum("status").notNull().default("active"),

  /**
   * Display fields cached from Clerk for performance.
   * Nullable — Clerk is the source of truth for these values.
   * Updated on each successful /v1/auth/me call.
   */
  displayName: text("display_name"),
  email: text("email"),
  avatarUrl: text("avatar_url"),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type AccountType = (typeof accountTypeEnum.enumValues)[number];
export type ProviderKind = (typeof providerKindEnum.enumValues)[number];
export type UserStatus = (typeof userStatusEnum.enumValues)[number];

/** Account types that can be chosen during public self-registration. */
export const PUBLIC_ACCOUNT_TYPES: AccountType[] = ["employer", "provider"];

/** Account types reserved for internal staff — never accessible via public API. */
export const INTERNAL_ACCOUNT_TYPES: AccountType[] = [
  "owner",
  "system_admin",
  "verification_team",
  "support_team",
  "moderation_team",
];

export function isPublicAccountType(v: string): v is "employer" | "provider" {
  return v === "employer" || v === "provider";
}
