/**
 * Payment provider abstraction — Stage 8.
 *
 * The application depends only on the PaymentProvider interface.
 * Paystack, Stripe, or any other provider can be swapped in by
 * changing only the adapter — no route or service code changes.
 *
 * Tests inject the MockPaymentProvider; production uses PaystackProvider.
 */

// ─── Checkout ─────────────────────────────────────────────────────────────────

export interface InitializeCheckoutParams {
  /** User's email — sent to the provider for receipt delivery. */
  email: string;
  /** Amount in integer minor units (e.g. kobo for NGN). */
  amountMinor: number;
  /** ISO 4217 currency code (e.g. 'NGN'). */
  currency: string;
  /** Unique reference generated by this backend. */
  reference: string;
  /** Optional URL the provider redirects to after payment. */
  callbackUrl?: string;
  /** Arbitrary key/value pairs forwarded to the provider. */
  metadata?: Record<string, unknown>;
}

export interface CheckoutResult {
  /** Provider-hosted payment page URL — redirect the user here. */
  authorizationUrl: string;
  /** The reference echoed back for confirmation. */
  reference: string;
}

// ─── Verification ─────────────────────────────────────────────────────────────

export type PaymentVerifyStatus = "success" | "failed" | "abandoned" | "pending";

export interface VerifyPaymentResult {
  reference: string;
  status: PaymentVerifyStatus;
  /** Amount in integer minor units as confirmed by the provider. */
  amountMinor: number;
  currency: string;
  /** Provider-assigned transaction ID — used for refunds and audit. */
  providerPaymentId: string;
  email: string;
  paidAt?: string;
}

// ─── Webhooks ─────────────────────────────────────────────────────────────────

export interface WebhookVerifyResult {
  /** True when the signature is valid. False = reject the event immediately. */
  valid: boolean;
  /** Provider-assigned unique event ID — used for idempotency. */
  eventId: string;
  /** e.g. 'charge.success', 'subscription.disable' */
  eventType: string;
  /** The payment reference, if present in the event payload. */
  reference?: string;
  status?: PaymentVerifyStatus;
  /** Amount in minor units from the event payload. */
  amountMinor?: number;
  /** Provider-assigned transaction ID from the event payload. */
  providerPaymentId?: string;
}

// ─── Provider interface ───────────────────────────────────────────────────────

export interface PaymentProvider {
  /**
   * Initialize a hosted checkout session.
   * Returns a URL the user should be redirected to.
   */
  initializeCheckout(params: InitializeCheckoutParams): Promise<CheckoutResult>;

  /**
   * Verify the status of a payment by its reference.
   * Called to confirm a payment before activating an entitlement.
   */
  verifyPayment(reference: string): Promise<VerifyPaymentResult>;

  /**
   * Verify a provider webhook signature and parse the event.
   *
   * @param rawBody   Raw request body as a string (before JSON parsing).
   * @param signature Value of the provider-specific signature header.
   */
  verifyWebhook(rawBody: string, signature: string): Promise<WebhookVerifyResult>;
}
