/**
 * Billing service — Stage 8.
 *
 * Orchestrates repositories and enforces business rules.
 * No route handler touches repositories directly.
 *
 * Business rules enforced here:
 *   - Plan amount and currency come from the server-side catalog — never from clients.
 *   - Users can only initiate checkout for active plans.
 *   - Only the webhook handler may mark a payment as succeeded.
 *   - Entitlements are derived entirely from subscription status — never from client claims.
 *   - Users can only read their own billing data.
 *
 * Subscriptions are currently on standby: the architecture is fully in place
 * but payment provider keys are not yet configured. Checkout will fail at the
 * provider call if PAYSTACK_SECRET_KEY is not set; all read endpoints work
 * regardless of provider key status.
 */

import { randomUUID } from "crypto";
import type { Db } from "../../db/client.js";
import { BadRequestError, NotFoundError } from "../../errors/index.js";
import type { PaymentProvider } from "../../lib/payment/index.js";
import {
  listActivePlans,
  getPlanById,
  getSubscriptionForUser,
  upsertSubscription,
  updateSubscriptionStatus,
  insertPaymentIntent,
  getIntentByReference,
  updatePaymentIntentStatus,
  listPaymentIntentsForUser,
  insertWebhookEventIfNew,
  markWebhookEventProcessed,
} from "./repository.js";
import {
  toPlanDto,
  toSubscriptionDto,
  toPaymentIntentDto,
  type PlanDto,
  type EntitlementsDto,
  type MyBillingDto,
  type CheckoutDto,
  type InitCheckoutParams,
} from "./types.js";

// ─── Plans ────────────────────────────────────────────────────────────────────

/** Return all active subscription plans. Public endpoint — no auth required. */
export async function getActivePlans(db: Db): Promise<PlanDto[]> {
  const rows = await listActivePlans(db);
  return rows.map(toPlanDto);
}

// ─── Checkout ─────────────────────────────────────────────────────────────────

/**
 * Initialize a Paystack checkout session for the given plan.
 *
 * Security:
 *   - Plan amount and currency are read from the DB catalog — the client only
 *     supplies the plan ID. They cannot influence the price.
 *   - The provider reference is generated by this backend and stored before
 *     the provider call, so webhook callbacks can be correlated securely.
 */
export async function initializeCheckout(
  db: Db,
  provider: PaymentProvider,
  params: InitCheckoutParams,
): Promise<CheckoutDto> {
  const plan = await getPlanById(db, params.planId);
  if (!plan) throw new NotFoundError("Plan");
  if (!plan.isActive) throw new BadRequestError("This plan is not currently available.");
  if (plan.amountMinor === 0) {
    throw new BadRequestError("Free plans do not require a checkout. Use the free plan directly.");
  }

  // Generate reference on our side — never from the client.
  const reference = `pmp_${randomUUID().replace(/-/g, "")}`;

  const checkoutParams: Parameters<typeof provider.initializeCheckout>[0] = {
    email: params.email,
    amountMinor: plan.amountMinor,
    currency: plan.currency,
    reference,
  };
  if (params.callbackUrl !== undefined) checkoutParams.callbackUrl = params.callbackUrl;
  const checkout = await provider.initializeCheckout(checkoutParams);

  const intentId = randomUUID();
  await insertPaymentIntent(db, {
    id: intentId,
    userId: params.userId,
    planId: plan.id,
    amountMinor: plan.amountMinor, // snapshot — immune to plan price changes
    currency: plan.currency,
    providerReference: reference,
    authorizationUrl: checkout.authorizationUrl,
  });

  return {
    authorizationUrl: checkout.authorizationUrl,
    reference,
    paymentIntentId: intentId,
  };
}

// ─── My billing ───────────────────────────────────────────────────────────────

/** Return the calling user's subscription and recent payment history. */
export async function getMyBilling(db: Db, userId: string): Promise<MyBillingDto> {
  const [subRow, intentRows] = await Promise.all([
    getSubscriptionForUser(db, userId),
    listPaymentIntentsForUser(db, userId),
  ]);

  return {
    subscription: subRow ? toSubscriptionDto(subRow) : null,
    recentPayments: intentRows.map(toPaymentIntentDto),
  };
}

// ─── Entitlements ─────────────────────────────────────────────────────────────

/**
 * Return the entitlements for the calling user.
 *
 * Security: derived entirely from the DB subscription record.
 * The frontend cannot influence this result.
 */
export async function getEntitlements(db: Db, userId: string): Promise<EntitlementsDto> {
  const sub = await getSubscriptionForUser(db, userId);

  const hasActive = sub !== null && (sub.status === "active" || sub.status === "trialing");

  return {
    hasActiveSubscription: hasActive,
    planId: sub?.planId ?? null,
    planName: sub?.planName ?? null,
    accessUntil: sub?.currentPeriodEnd?.toISOString() ?? null,
  };
}

// ─── Webhook processing ───────────────────────────────────────────────────────

/**
 * Process a verified webhook event from the payment provider.
 *
 * Security invariants:
 *   - The caller (route handler) MUST verify the webhook signature before calling this.
 *   - Idempotency: duplicate event IDs are ignored at the DB level.
 *   - Subscription state is set only from provider event data — never from client input.
 *   - Invalid payment transitions do not throw; they are logged and ignored.
 */
export async function processWebhookEvent(
  db: Db,
  provider: string,
  event: {
    eventId: string;
    eventType: string;
    reference?: string;
    status?: string;
    amountMinor?: number;
    providerPaymentId?: string;
    rawPayload: unknown;
  },
): Promise<{ processed: boolean; reason?: string }> {
  // 1. Record the event — unique constraint guards against duplicate processing.
  const isNew = await insertWebhookEventIfNew(db, {
    id: randomUUID(),
    provider,
    eventId: event.eventId,
    eventType: event.eventType,
    payload: event.rawPayload,
  });

  if (!isNew) {
    return { processed: false, reason: "duplicate" };
  }

  // 2. Handle known event types.
  if (event.eventType === "charge.success" && event.reference) {
    const intent = await getIntentByReference(db, event.reference);
    if (!intent) {
      await markWebhookEventProcessed(db, provider, event.eventId);
      return { processed: false, reason: "intent_not_found" };
    }

    // Update intent to succeeded.
    await updatePaymentIntentStatus(db, intent.id, "succeeded", event.providerPaymentId);

    // Activate or upgrade the user's subscription.
    const upsertParams: Parameters<typeof upsertSubscription>[1] = {
      id: randomUUID(),
      userId: intent.userId,
      planId: intent.planId,
      status: "active",
      currentPeriodStart: new Date(),
      // Default: 30-day period. In production, use the provider's period dates.
      currentPeriodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    };
    if (event.providerPaymentId !== undefined) {
      upsertParams.providerSubscriptionId = event.providerPaymentId;
    }
    await upsertSubscription(db, upsertParams);

    await markWebhookEventProcessed(db, provider, event.eventId);
    return { processed: true };
  }

  if (
    (event.eventType === "subscription.disable" || event.eventType === "subscription.not_renew") &&
    event.reference
  ) {
    const intent = await getIntentByReference(db, event.reference);
    if (intent) {
      await updateSubscriptionStatus(db, intent.userId, "cancelled", new Date());
    }
    await markWebhookEventProcessed(db, provider, event.eventId);
    return { processed: true };
  }

  if (event.eventType === "charge.failed" && event.reference) {
    const intent = await getIntentByReference(db, event.reference);
    if (intent) {
      await updatePaymentIntentStatus(db, intent.id, "failed", event.providerPaymentId);
    }
    await markWebhookEventProcessed(db, provider, event.eventId);
    return { processed: true };
  }

  // Unknown event type — recorded but not acted on.
  await markWebhookEventProcessed(db, provider, event.eventId);
  return { processed: false, reason: "unhandled_event_type" };
}
